site_name: Web Application Security
repo_url: https://github.com/andreashappe/web-security
theme:
  name: material
  features:
    - navigation.sections
    - navigation.tracking
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: de
markdown_extensions:
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/andreashappe/web-security
  analytics:
    provider: google
    property: G-8KL7RKRNSS

nav:
  - 'Intro': index.md
  - 'How to Contribute': todo.md
  - 'Einführung':
    - 'Grundprinzipien': introduction/security_principles.md
    - 'Sicherheit als Prozess': introduction/security_as_process.md
    - 'Integration mit dem Umfeld': introduction/integration.md
    - 'Kryptographische Grundlagen': introduction/crypto_basics.md
  - 'Web Grundlagen':
    - 'Technologien': web-applications/web_technologies.md
    - 'Web Applikationen': web-applications/web_applications.md
  - 'Zugriffskontrolle':
    - 'Identifikation und Authentifizierung': authentication-and-authorization/authentication.md
    - 'Session-Management': authentication-and-authorization/session_management.md
    - 'Autorisierung': authentication-and-authorization/authorization.md
    - 'Single-Sign On (SSO)': authentication-and-authorization/sso.md
  - 'Server-Seitige Angriffe':
    - 'Allgemeines': server-side-attacks/allgemein.md
    - 'File-Uploads': server-side-attacks/file-uploads.md
    - 'Path-Traversals': server-side-attacks/path-traversals.md
    - 'Command-Injections': server-side-attacks/command-injections.md
    - 'Database-Injections': server-side-attacks/database-injections.md
    - 'LDAP-Injections': server-side-attacks/ldap-injections.md
    - 'Type Juggling': server-side-attacks/type-juggling.md
    - 'XML-basierte Angriffe': server-side-attacks/xml-based-attacks.md
    - 'Serialisierungs-Angriffe': server-side-attacks/serialization-attacks.md
    - 'Request Smuggling': server-side-attacks/http-request-smuggling.md
    - 'SSTI': server-side-attacks/SSTI.md
  - 'Client-Seitige Angriffe':
    - 'Angriffe': client-side-attacks/client_side_attacks.md
    - 'Härtungsmaßnahmen': client-side-attacks/client_side_hardening.md
  - 'Appendix':
    - 'Apache mod_security': appendix/mod_security.md
    - 'Entstehungsgeschichte': appendix/history.md
    - 'What to do next?': appendix/weitere-informationen.md